export const profileList = [
  {
    id: 1,
    nick: "팀장 김웨이",
    name: "김웨이",
    img: "card_profile_1.png",
    count: "999",
    rate: "99",
    isLeader: true,
    accreditABO: true,
  },
  {
    id: 2,
    nick: "유리카",
    name: "김사무엘 유리카 닉슨",
    img: "card_profile_2.png",
    count: "223",
    rate: "74",
    isLeader: false,
    accreditABO: false,
  },
  {
    id: 3,
    nick: "다니엘",
    name: "다니엘 빌",
    img: "card_profile_3.png",
    count: "223",
    rate: "52",
    isLeader: false,
    accreditABO: true,
  },
  {
    id: 4,
    nick: "코니",
    name: "코니 일렉스",
    img: "card_profile_4.png",
    count: "223",
    rate: "29",
    isLeader: false,
    accreditABO: true,
  },
  {
    id: 5,
    nick: "김사무엘 주니어",
    name: "김별리",
    img: "card_profile_4.png",
    count: "223",
    rate: "10",
    isLeader: false,
    accreditABO: false,
  },
  {
    id: 6,
    nick: "김사무엘 주니어",
    name: "김별리",
    img: "card_profile_4.png",
    count: "223",
    rate: "10",
    isLeader: false,
    accreditABO: false,
  },
  {
    id: 7,
    nick: "김사무엘 주니어",
    name: "김별리",
    img: "card_profile_4.png",
    count: "223",
    rate: "10",
    isLeader: false,
    accreditABO: false,
  },
  {
    id: 8,
    nick: "김사무엘 주니어",
    name: "김별리",
    img: "card_profile_4.png",
    count: "223",
    rate: "10",
    isLeader: false,
    accreditABO: false,
  },
];
